### ISSUE TITLE
Arrow function syntax

### ISSUE THREAD

**Issue by johangithub** [ganders3/jmt#1]
I noticed that you use arrow functions, and sometimes they can be more concise if you wish.

```js
matches.sort((a,b)=>{
  return(a.jobInd - b.jobInd)
}
```
can be
```js
matches.sort((a,b) => a.jobInd - b.jobInd)
```

Also, `()` around one variable is optional, so
```js
let qwUnmatched = qw.filter((person) => {
	return(person.filledJob.length == 0);
});
```
can be
```js
let qwUnmatched = qw.filter(person => person.filledJob.length == 0);
```

**Comment by ganders3** [comment]
Cool, thanks. I'll have to get more familiar cause right now I can barely interpret what your shorthand functions are doing if I didn't have the original to compare to.
